### ISSUE TITLE
Error running make

### ISSUE THREAD

**Issue by vladrmnv** [tlehman/newtonian#1]
Hi, 

This is the error I get when I run make 

`make

bin/download_websocketd.sh

bin/download_websocketd.sh: 6: bin/download_websocketd.sh: function: not found
linux  

bin/download_websocketd.sh: 8: bin/download_websocketd.sh: Syntax error: "}" unexpected
make: **\* [tmp/websocketd.zip] Error 2`

**Comment by vladrmnv** [comment]
I was running it on c9.io, worked on local machine

**Comment by tlehman** [comment]
Sweet
