### ISSUE TITLE
Websocket address in newtonian.js

### ISSUE THREAD

**Issue by vladrmnv** [tlehman/newtonian#2]
Line 42 in newtonian.js should specify the socket server address, how is it possible to find it for specific loacl machine? Shouldn't it be localhost? 

`var ws = new WebSocket("ws://hausdorff.local:8080/");`

**Comment by tlehman** [comment]
Yes, I was using that address so others on my LAN could use it, thanks for finding that. I've replaced it with localhost so it should work for others now.
